# Welcome!

## I would be dealing with the dataset, using Bi-directional LSTM Approach, Please have a look at my Notebook, if you liked it, please do UpVote!

In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('../input/real-or-fake-fake-jobposting-prediction/fake_job_postings.csv')
df1.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [3]:
df1.shape

(17880, 18)

In [4]:
df=df1[['description','requirements','fraudulent']]
df.head()

,description,requirements,fraudulent
0,"Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,0
1,Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,0
2,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,0
3,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",0
4,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,0

In [5]:
###Drop Nan Values
df=df.dropna()

In [6]:
df.shape

(15185, 3)

In [7]:
## Get the Independent Features

X=df.drop('fraudulent',axis=1)

In [8]:
## Get the Dependent features
y=df['fraudulent']

In [9]:
y.value_counts()

0    14473
1      712
Name: fraudulent, dtype: int64

In [10]:
import tensorflow as tf
tf.__version__

'2.2.0'

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [12]:
voc_size=5000

## Onehot Representation:

In [13]:
message = X.copy()

In [14]:
message['description'][1]

"Organised - Focused - Vibrant - Awesome!Do you have a passion for customer service? Slick typing skills? Maybe Account Management? ...And think administration is cooler than a polar bear on a jetski? Then we need to hear you!\xa0We are the Cloud Video Production Service and opperating on a glodal level. Yeah, it's pretty cool. Serious about\xa0delivering a world class product and excellent customer service.Our rapidly expanding business is looking for a talented Project Manager to manage the successful delivery of video projects, manage client communications and drive the production process. Work with some of the coolest brands on the planet and learn from a global team that are representing NZ is a huge way!We are entering the next growth stage of our business and growing quickly internationally. \xa0Therefore, the position is bursting with opportunity for the right person entering the business at the right time.\xa090 Seconds, the worlds Cloud Video Production Service -\xa0http://90#URL_fbe6559afac620a3cd2c22281f7b8d0eef56a73e3d9a311e2f1ca13d081dd630#90 Seconds is the worlds Cloud Video Production Service enabling brands and agencies to get high quality online video content shot and produced anywhere in the world. Fast, affordable, and all managed seamlessly in the cloud from purchase to publish.\xa090 Seconds removes the hassle, cost, risk and speed issues of working with regular video production companies by managing every aspect of video projects in a beautiful online experience. \xa0With a growing network of over 2,000 rated video professionals in over 50 countries and dedicated production success teams in 5 countries guaranteeing video project success 100%. It's as easy as commissioning a quick google adwords campaign.90 Seconds has produced almost 4,000 videos in over 30 Countries for over 500 Global brands including some of the worlds largest including Paypal, L'oreal, Sony and Barclays and has offices in Auckland, London, Sydney, Tokyo &amp; Singapore.Our Auckland office is based\xa0right in the heart of the Wynyard Quarter Innovation Precinct - GridAKL!\xa0"

In [15]:
message.reset_index(inplace=True)

In [16]:
import nltk
import re
from nltk.corpus import stopwords

In [17]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['description'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [18]:
corpus[1]

'organis focus vibrant awesom passion custom servic slick type skill mayb account manag think administr cooler polar bear jetski need hear cloud video product servic opper glodal level yeah pretti cool seriou deliv world class product excel custom servic rapidli expand busi look talent project manag manag success deliveri video project manag client commun drive product process work coolest brand planet learn global team repres nz huge way enter next growth stage busi grow quickli intern therefor posit burst opportun right person enter busi right time second world cloud video product servic http url fbe afac cd c f b eef e e f ca dd second world cloud video product servic enabl brand agenc get high qualiti onlin video content shot produc anywher world fast afford manag seamlessli cloud purchas publish second remov hassl cost risk speed issu work regular video product compani manag everi aspect video project beauti onlin experi grow network rate video profession countri dedic product success team countri guarante video project success easi commiss quick googl adword campaign second produc almost video countri global brand includ world largest includ paypal l oreal soni barclay offic auckland london sydney tokyo amp singapor auckland offic base right heart wynyard quarter innov precinct gridakl'

In [19]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr[1]

[2974,
 4474,
 4437,
 78,
 930,
 1709,
 3660,
 699,
 4144,
 4321,
 1432,
 3456,
 3224,
 1097,
 305,
 3930,
 927,
 363,
 2110,
 2589,
 4615,
 1648,
 4092,
 1774,
 3660,
 2684,
 319,
 4720,
 482,
 1907,
 4698,
 991,
 706,
 2463,
 1858,
 1774,
 1117,
 1709,
 3660,
 2611,
 2174,
 2519,
 882,
 989,
 3144,
 3224,
 3224,
 606,
 494,
 4092,
 3144,
 3224,
 1263,
 4141,
 2789,
 1774,
 4923,
 1142,
 944,
 759,
 251,
 4525,
 2949,
 2427,
 339,
 4922,
 3511,
 4592,
 2914,
 2987,
 1905,
 1705,
 2519,
 2448,
 3446,
 2633,
 3404,
 2016,
 4467,
 3486,
 2726,
 1063,
 2914,
 2519,
 2726,
 1017,
 4476,
 2463,
 1648,
 4092,
 1774,
 3660,
 1378,
 3876,
 2168,
 4056,
 557,
 452,
 2864,
 181,
 2365,
 3764,
 3764,
 2864,
 1662,
 3137,
 4476,
 2463,
 1648,
 4092,
 1774,
 3660,
 3596,
 759,
 1224,
 1566,
 466,
 4363,
 2759,
 4092,
 3646,
 3974,
 4598,
 4650,
 2463,
 2036,
 3170,
 3224,
 4846,
 1648,
 3056,
 52,
 4476,
 3691,
 3102,
 1015,
 3252,
 4770,
 513,
 1142,
 2991,
 4092,
 1774,
 3257,
 3224,
 4322,
 4612,
 4092,
 3144,
 2452,
 2759,
 492,
 2448,
 4324,
 379,
 4092,
 1244,
 1802,
 1352,
 1774,
 606,
 2427,
 1802,
 2199,
 4092,
 3144,
 606,
 4004,
 3408,
 737,
 3998,
 776,
 1816,
 4476,
 4598,
 2740,
 4092,
 1802,
 2949,
 759,
 4415,
 2463,
 3314,
 4415,
 1855,
 1250,
 2640,
 2916,
 58,
 3352,
 2806,
 2976,
 4597,
 602,
 1015,
 777,
 2806,
 3352,
 760,
 2726,
 805,
 2796,
 388,
 1985,
 2574,
 2621]

## Embedding Representation:

In [20]:
sent_length=40
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[3474 3646 3224 ...  164 3371  848]
 [ 606 4004 3408 ... 1985 2574 2621]
 [   0    0    0 ... 4968  689  705]
 ...
 [1723 4152 2380 ... 1911 3141  604]
 [1384 2001 3101 ...  898 2633 3144]
 [ 510 2936 2465 ... 1236 1776 3296]]

In [21]:
embedded_docs[0]

array([3474, 3646, 3224, 2615, 4942, 1184,  735, 1378, 3315, 4057,  147,
        147, 3315,  533,  590,  599, 3315, 3152, 3315, 2590, 4742, 1015,
        844,  938, 3352,  305, 1142, 2642, 3020, 1216, 4153,  640, 3214,
       3826,  168, 3889, 2238,  164, 3371,  848], dtype=int32)

In [22]:
## Creating model
embedding_vector_features=50
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100))) ##Just add bidirectional!!, except it would just behave as normal LSTM Model
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
embedding (Embedding)        (None, 40, 50)            250000
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               120800
_________________________________________________________________
dropout (Dropout)            (None, 200)               0
_________________________________________________________________
dense (Dense)                (None, 1)                 201
=================================================================
Total params: 371,001
Trainable params: 371,001
Non-trainable params: 0
_________________________________________________________________
None

In [23]:
len(embedded_docs),y.shape

(15185, (15185,))

In [24]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [25]:
X_final[1]

array([ 606, 4004, 3408,  737, 3998,  776, 1816, 4476, 4598, 2740, 4092,
       1802, 2949,  759, 4415, 2463, 3314, 4415, 1855, 1250, 2640, 2916,
         58, 3352, 2806, 2976, 4597,  602, 1015,  777, 2806, 3352,  760,
       2726,  805, 2796,  388, 1985, 2574, 2621], dtype=int32)

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.25, random_state=32)

In [27]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=12,batch_size=64)

Epoch 1/12
178/178 [==============================] - 3s 16ms/step - loss: 0.1848 - accuracy: 0.9577 - val_loss: 0.1469 - val_accuracy: 0.9594
Epoch 2/12
178/178 [==============================] - 2s 12ms/step - loss: 0.0822 - accuracy: 0.9766 - val_loss: 0.1430 - val_accuracy: 0.9629
Epoch 3/12
178/178 [==============================] - 2s 11ms/step - loss: 0.0531 - accuracy: 0.9843 - val_loss: 0.1811 - val_accuracy: 0.9655
Epoch 4/12
178/178 [==============================] - 2s 13ms/step - loss: 0.0327 - accuracy: 0.9908 - val_loss: 0.1550 - val_accuracy: 0.9666
Epoch 5/12
178/178 [==============================] - 2s 12ms/step - loss: 0.0212 - accuracy: 0.9934 - val_loss: 0.1562 - val_accuracy: 0.9637
Epoch 6/12
178/178 [==============================] - 2s 12ms/step - loss: 0.0162 - accuracy: 0.9949 - val_loss: 0.2360 - val_accuracy: 0.9668
Epoch 7/12
178/178 [==============================] - 2s 12ms/step - loss: 0.0087 - accuracy: 0.9975 - val_loss: 0.2154 - val_accuracy: 0.9671
Epoch 8/12
178/178 [==============================] - 2s 13ms/step - loss: 0.0075 - accuracy: 0.9981 - val_loss: 0.2105 - val_accuracy: 0.9655
Epoch 9/12
178/178 [==============================] - 2s 12ms/step - loss: 0.0059 - accuracy: 0.9982 - val_loss: 0.1883 - val_accuracy: 0.9605
Epoch 10/12
178/178 [==============================] - 2s 12ms/step - loss: 0.0039 - accuracy: 0.9989 - val_loss: 0.1955 - val_accuracy: 0.9666
Epoch 11/12
178/178 [==============================] - 2s 11ms/step - loss: 0.0035 - accuracy: 0.9989 - val_loss: 0.3111 - val_accuracy: 0.9655
Epoch 12/12
178/178 [==============================] - 2s 12ms/step - loss: 0.0032 - accuracy: 0.9992 - val_loss: 0.2602 - val_accuracy: 0.9658

## Model Performance and Accuracy:

In [28]:
y_pred=model1.predict_classes(X_test)

In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[3556,   29],
       [ 101,  111]])

In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9657624440347643

In [31]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      3585
           1       0.79      0.52      0.63       212

    accuracy                           0.97      3797
   macro avg       0.88      0.76      0.81      3797
weighted avg       0.96      0.97      0.96      3797

## If you like my appoach, please give a UpVote!

## Thankyou so much !